#pragma once
#include <stdint.h>

static uint32_t WeapHashes[] = { 0x99B507EA, 0x678B81B1, 0x4E875F73, 0x958A4A8F, 0x440E4788, 0x84BD7BFD, 0x1B06D571, 0x5EF9FEC4, 0x22D8FE39,
0x99AEEB3B, 0x13532244, 0x2BE6766B, 0xEFE7E2DF, 0xBFEFFF6D, 0x83BF0278, 0xAF113F99, 0x9D07F764, 0x7FD62962, 0x1D073A89, 0x7846A318,
0xE284C527, 0x9D61E50F, 0x3656C8C1, 0x05FC3C11, 0x0C472FE2, 0x33058E22, 0xA284510B, 0x4DD2DC56, 0xB1CA77B1, 0x687652CE, 0x42BF8A85,
0x93E220BD, 0x2C3731D9, 0xFDBC8A50, 0x24B17070, 0x060EC506, 0x34A67B97, 0xFDBADCED, 0x23C9F95C, 0x497FACC3, 0xF9E6AA4B, 0x61012683,
0xC0A3098D, 0xD205520E, 0xBFD21232, 0x7F229F94, 0x92A27487, 0x083839C4, 0x7F7497E5, 0xA89CB99E, 0x3AABBBAA, 0xC734385A, 0x787F0BB,
0x47757124, 0xD04C944D };

static std::string vehicleModels[] = {
	"NINEF", "NINEF2", "BLISTA", "ASEA", "ASEA2", "BOATTRAILER", "BUS", "ARMYTANKER", "ARMYTRAILER", "ARMYTRAILER2",
	"SUNTRAP", "COACH", "AIRBUS", "ASTEROPE", "AIRTUG", "AMBULANCE", "BARRACKS", "BARRACKS2", "BALLER", "BALLER2",
	"BJXL", "BANSHEE", "BENSON", "BFINJECTION", "BIFF", "BLAZER", "BLAZER2", "BLAZER3", "BISON", "BISON2",
	"BISON3", "BOXVILLE", "BOXVILLE2", "BOXVILLE3", "BOBCATXL", "BODHI2", "BUCCANEER", "BUFFALO", "BUFFALO2", "BULLDOZER",
	"BULLET", "BLIMP", "BURRITO", "BURRITO2", "BURRITO3", "BURRITO4", "BURRITO5", "CAVALCADE", "CAVALCADE2", "POLICET",
	"GBURRITO", "CABLECAR", "CADDY", "CADDY2", "CAMPER", "CARBONIZZARE", "CHEETAH", "COMET2", "COGCABRIO", "COQUETTE",
	"CUTTER", "GRESLEY", "DILETTANTE", "DILETTANTE2", "DUNE", "DUNE2", "HOTKNIFE", "DLOADER", "DUBSTA", "DUBSTA2",
	"DUMP", "RUBBLE", "DOCKTUG", "DOMINATOR", "EMPEROR", "EMPEROR2", "EMPEROR3", "ENTITYXF", "EXEMPLAR", "ELEGY2",
	"F620", "FBI", "FBI2", "FELON", "FELON2", "FELTZER2", "FIRETRUK", "FLATBED", "FORKLIFT", "FQ2",
	"FUSILADE", "FUGITIVE", "FUTO", "GRANGER", "GAUNTLET", "HABANERO", "HAULER", "HANDLER", "INFERNUS", "INGOT",
	"INTRUDER", "ISSI2", "JACKAL", "JOURNEY", "JB700", "KHAMELION", "LANDSTALKER", "LGUARD", "MANANA", "MESA",
	"MESA2", "MESA3", "CRUSADER", "MINIVAN", "MIXER", "MIXER2", "MONROE", "MOWER", "MULE", "MULE2",
	"ORACLE", "ORACLE2", "PACKER", "PATRIOT", "PBUS", "PENUMBRA", "PEYOTE", "PHANTOM", "PHOENIX", "PICADOR",
	"POUNDER", "POLICE", "POLICE4", "POLICE2", "POLICE3", "POLICEOLD1", "POLICEOLD2", "PONY", "PONY2", "PRAIRIE",
	"PRANGER", "PREMIER", "PRIMO", "PROPTRAILER", "RANCHERXL", "RANCHERXL2", "RAPIDGT", "RAPIDGT2", "RADI", "RATLOADER",
	"REBEL", "REGINA", "REBEL2", "RENTALBUS", "RUINER", "RUMPO", "RUMPO2", "RHINO", "RIOT", "RIPLEY",
	"ROCOTO", "ROMERO", "SABREGT", "SADLER", "SADLER2", "SANDKING", "SANDKING2", "SCHAFTER2", "SCHWARZER", "SCRAP",
	"SEMINOLE", "SENTINEL", "SENTINEL2", "ZION", "ZION2", "SERRANO", "SHERIFF", "SHERIFF2", "SPEEDO", "SPEEDO2",
	"STANIER", "STINGER", "STINGERGT", "STOCKADE", "STOCKADE3", "STRATUM", "SULTAN", "SUPERD", "SURANO", "SURFER",
	"SURFER2", "SURGE", "TACO", "TAILGATER", "TAXI", "TRASH", "TRACTOR", "TRACTOR2", "TRACTOR3", "GRAINTRAILER",
	"BALETRAILER", "TIPTRUCK", "TIPTRUCK2", "TORNADO", "TORNADO2", "TORNADO3", "TORNADO4", "TOURBUS", "TOWTRUCK", "TOWTRUCK2",
	"UTILLITRUCK", "UTILLITRUCK2", "UTILLITRUCK3", "VOODOO2", "WASHINGTON", "STRETCH", "YOUGA", "ZTYPE", "SANCHEZ", "SANCHEZ2",
	"SCORCHER", "TRIBIKE", "TRIBIKE2", "TRIBIKE3", "FIXTER", "CRUISER", "BMX", "POLICEB", "AKUMA", "CARBONRS",
	"BAGGER", "BATI", "BATI2", "RUFFIAN", "DAEMON", "DOUBLE", "PCJ", "VADER", "VIGERO", "FAGGIO2",
	"HEXER", "ANNIHILATOR", "BUZZARD", "BUZZARD2", "CARGOBOB", "CARGOBOB2", "CARGOBOB3", "SKYLIFT", "POLMAV", "MAVERICK",
	"NEMESIS", "FROGGER", "FROGGER2", "CUBAN800", "DUSTER", "STUNT", "MAMMATUS", "JET", "SHAMAL", "LUXOR",
	"TITAN", "LAZER", "CARGOPLANE", "SQUALO", "MARQUIS", "DINGHY", "DINGHY2", "JETMAX", "PREDATOR", "TROPIC",
	"SEASHARK", "SEASHARK2", "SUBMERSIBLE", "TRAILERS", "TRAILERS2", "TRAILERS3", "TVTRAILER", "RAKETRAILER", "TANKER", "TRAILERLOGS",
	"TR2", "TR3", "TR4", "TRFLAT", "TRAILERSMALL", "VELUM", "ADDER", "VOLTIC", "VACCA", "BIFTA",
	"SPEEDER", "PARADISE", "KALAHARI", "JESTER", "TURISMOR", "VESTRA", "ALPHA", "HUNTLEY", "THRUST", "MASSACRO",
	"MASSACRO2", "ZENTORNO", "BLADE", "GLENDALE", "PANTO", "PIGALLE", "WARRENER", "RHAPSODY", "DUBSTA3", "MONSTER",
	"SOVEREIGN", "INNOVATION", "HAKUCHOU", "FUROREGT", "MILJET", "COQUETTE2", "BTYPE", "BUFFALO3", "DOMINATOR2", "GAUNTLET2",
	"MARSHALL", "DUKES", "DUKES2", "STALION", "STALION2", "BLISTA2", "BLISTA3", "DODO", "SUBMERSIBLE2", "HYDRA",
	"INSURGENT", "INSURGENT2", "TECHNICAL", "SAVAGE", "VALKYRIE", "KURUMA", "KURUMA2", "JESTER2", "CASCO", "VELUM2",
	"GUARDIAN", "ENDURO", "LECTRO", "SLAMVAN", "SLAMVAN2", "RATLOADER2", "SWIFT2", "LUXOR2", "FELTZER3", "OSIRIS",
	"VIRGO", "WINDSOR", "BESRA", "SWIFT", "BLIMP2", "VINDICATOR", "TORO", "T20", "COQUETTE3", "CHINO",
	"BRAWLER" 
};

static std::string pedModels[] = { 
	"a_c_boar","a_c_chickenhawk","a_c_chimp","a_c_chop","a_c_cormorant","a_c_cow","a_c_coyote",
	"a_c_crow","a_c_deer","a_c_fish","a_c_hen","a_c_husky","a_c_mtlion","a_c_pig","a_c_pigeon","a_c_rat","a_c_retriever","a_c_rhesus",
	"a_c_rottweiler","a_c_seagull","a_c_sharktiger","a_c_shepherd","a_f_m_beach_01","a_f_m_bevhills_01","a_f_m_bevhills_02","a_f_m_bodybuild_01",
	"a_f_m_business_02","a_f_m_downtown_01","a_f_m_eastsa_01","a_f_m_eastsa_02","a_f_m_fatbla_01","a_f_m_fatcult_01","a_f_m_fatwhite_01",
	"a_f_m_ktown_01","a_f_m_ktown_02","a_f_m_prolhost_01","a_f_m_salton_01","a_f_m_skidrow_01","a_f_m_soucent_01","a_f_m_soucent_02",
	"a_f_m_soucentmc_01","a_f_m_tourist_01","a_f_m_tramp_01","a_f_m_trampbeac_01","a_f_o_genstreet_01","a_f_o_indian_01","a_f_o_ktown_01",
	"a_f_o_salton_01","a_f_o_soucent_01","a_f_o_soucent_02","a_f_y_beach_01","a_f_y_bevhills_01","a_f_y_bevhills_02","a_f_y_bevhills_03",
	"a_f_y_bevhills_04","a_f_y_business_01","a_f_y_business_02","a_f_y_business_03","a_f_y_business_04","a_f_y_eastsa_01","a_f_y_eastsa_02",
	"a_f_y_eastsa_03","a_f_y_epsilon_01","a_f_y_fitness_01","a_f_y_fitness_02","a_f_y_genhot_01","a_f_y_golfer_01","a_f_y_hiker_01",
	"a_f_y_hippie_01","a_f_y_hipster_01","a_f_y_hipster_02","a_f_y_hipster_03","a_f_y_hipster_04","a_f_y_indian_01","a_f_y_juggalo_01",
	"a_f_y_runner_01","a_f_y_rurmeth_01","a_f_y_scdressy_01","a_f_y_skater_01","a_f_y_soucent_01","a_f_y_soucent_02","a_f_y_soucent_03",
	"a_f_y_tennis_01","a_f_y_topless_01","a_f_y_tourist_01","a_f_y_tourist_02","a_f_y_vinewood_01","a_f_y_vinewood_02","a_f_y_vinewood_03",
	"a_f_y_vinewood_04","a_f_y_yoga_01","a_m_m_acult_01","a_m_m_afriamer_01","a_m_m_beach_01","a_m_m_beach_02","a_m_m_bevhills_01",
	"a_m_m_bevhills_02","a_m_m_business_01","a_m_m_eastsa_01","a_m_m_eastsa_02","a_m_m_farmer_01","a_m_m_fatlatin_01","a_m_m_genfat_01",
	"a_m_m_genfat_02","a_m_m_golfer_01","a_m_m_hasjew_01","a_m_m_hillbilly_01","a_m_m_hillbilly_02","a_m_m_indian_01","a_m_m_ktown_01",
	"a_m_m_malibu_01","a_m_m_mexcntry_01","a_m_m_mexlabor_01","a_m_m_og_boss_01","a_m_m_paparazzi_01","a_m_m_polynesian_01","a_m_m_prolhost_01",
	"a_m_m_rurmeth_01","a_m_m_salton_01","a_m_m_salton_02","a_m_m_salton_03","a_m_m_salton_04","a_m_m_skater_01","a_m_m_skidrow_01",
	"a_m_m_socenlat_01","a_m_m_soucent_01","a_m_m_soucent_02","a_m_m_soucent_03","a_m_m_soucent_04","a_m_m_stlat_02","a_m_m_tennis_01",
	"a_m_m_tourist_01","a_m_m_tramp_01","a_m_m_trampbeac_01","a_m_m_tranvest_01","a_m_m_tranvest_02","a_m_o_acult_01","a_m_o_acult_02",
	"a_m_o_beach_01","a_m_o_genstreet_01","a_m_o_ktown_01","a_m_o_salton_01","a_m_o_soucent_01","a_m_o_soucent_02","a_m_o_soucent_03",
	"a_m_o_tramp_01","a_m_y_acult_01","a_m_y_acult_02","a_m_y_beach_01","a_m_y_beach_02","a_m_y_beach_03","a_m_y_beachvesp_01",
	"a_m_y_beachvesp_02","a_m_y_bevhills_01","a_m_y_bevhills_02","a_m_y_breakdance_01","a_m_y_busicas_01","a_m_y_business_01",
	"a_m_y_business_02","a_m_y_business_03","a_m_y_cyclist_01","a_m_y_dhill_01","a_m_y_downtown_01","a_m_y_eastsa_01","a_m_y_eastsa_02",
	"a_m_y_epsilon_01","a_m_y_epsilon_02","a_m_y_gay_01","a_m_y_gay_02","a_m_y_genstreet_01","a_m_y_genstreet_02","a_m_y_golfer_01",
	"a_m_y_hasjew_01","a_m_y_hiker_01","a_m_y_hippy_01","a_m_y_hipster_01","a_m_y_hipster_02","a_m_y_hipster_03","a_m_y_indian_01",
	"a_m_y_jetski_01","a_m_y_juggalo_01","a_m_y_ktown_01","a_m_y_ktown_02","a_m_y_latino_01","a_m_y_methhead_01","a_m_y_mexthug_01",
	"a_m_y_motox_01","a_m_y_motox_02","a_m_y_musclbeac_01","a_m_y_musclbeac_02","a_m_y_polynesian_01","a_m_y_roadcyc_01","a_m_y_runner_01",
	"a_m_y_runner_02","a_m_y_salton_01","a_m_y_skater_01","a_m_y_skater_02","a_m_y_soucent_01","a_m_y_soucent_02","a_m_y_soucent_03",
	"a_m_y_soucent_04","a_m_y_stbla_01","a_m_y_stbla_02","a_m_y_stlat_01","a_m_y_stwhi_01","a_m_y_stwhi_02","a_m_y_sunbathe_01",
	"a_m_y_surfer_01","a_m_y_vindouche_01","a_m_y_vinewood_01","a_m_y_vinewood_02","a_m_y_vinewood_03","a_m_y_vinewood_04","a_m_y_yoga_01",
	"csb_abigail","csb_anita","csb_anton","csb_ballasog","csb_bride","csb_burgerdrug","csb_car3guy1","csb_car3guy2","csb_chef","csb_chin_goon",
	"csb_cletus","csb_cop","csb_customer","csb_denise_friend","csb_fos_rep","csb_g","csb_groom","csb_grove_str_dlr","csb_hao","csb_hugh",
	"csb_imran","csb_janitor","csb_maude","csb_mweather","csb_ortega","csb_oscar","csb_porndudes","csb_prologuedriver","csb_prolsec",
	"csb_ramp_gang","csb_ramp_hic","csb_ramp_hipster","csb_ramp_marine","csb_ramp_mex","csb_reporter","csb_roccopelosi","csb_screen_writer",
	"csb_stripper_01","csb_stripper_02","csb_tonya","csb_trafficwarden","g_f_y_ballas_01","g_f_y_families_01","g_f_y_lost_01","g_f_y_vagos_01",
	"g_m_m_armboss_01","g_m_m_armgoon_01","g_m_m_armlieut_01","g_m_m_chemwork_01","g_m_m_chiboss_01","g_m_m_chicold_01","g_m_m_chigoon_01",
	"g_m_m_chigoon_02","g_m_m_korboss_01","g_m_m_mexboss_01","g_m_m_mexboss_02","g_m_y_armgoon_02","g_m_y_azteca_01","g_m_y_ballaeast_01",
	"g_m_y_ballaorig_01","g_m_y_ballasout_01","g_m_y_famca_01","g_m_y_famdnf_01","g_m_y_famfor_01","g_m_y_korean_01","g_m_y_korean_02",
	"g_m_y_korlieut_01","g_m_y_lost_01","g_m_y_lost_02","g_m_y_lost_03","g_m_y_mexgang_01","g_m_y_mexgoon_01","g_m_y_mexgoon_02","g_m_y_mexgoon_03",
	"g_m_y_pologoon_01","g_m_y_pologoon_02","g_m_y_salvaboss_01","g_m_y_salvagoon_01","g_m_y_salvagoon_02","g_m_y_salvagoon_03","g_m_y_strpunk_01",
	"g_m_y_strpunk_02","hc_driver","hc_gunman","hc_hacker","ig_abigail","ig_amandatownley","ig_andreas","ig_ashley","ig_ballasog","ig_bankman",
	"ig_barry","ig_bestmen","ig_beverly","ig_brad","ig_bride","ig_car3guy1","ig_car3guy2","ig_casey","ig_chef","ig_chengsr","ig_chrisformage","ig_clay",
	"ig_claypain","ig_cletus","ig_dale","ig_davenorton","ig_denise","ig_devin","ig_dom","ig_dreyfuss","ig_drfriedlander","ig_fabien","ig_fbisuit_01",
	"ig_floyd","ig_groom","ig_hao","ig_hunter","ig_janet","ig_jay_norris","ig_jewelass","ig_jimmyboston","ig_jimmydisanto","ig_joeminuteman",
	"ig_johnnyklebitz","ig_josef","ig_josh","ig_kerrymcintosh","ig_lamardavis","ig_lazlow","ig_lestercrest","ig_lifeinvad_01","ig_lifeinvad_02","ig_magenta",
	"ig_manuel","ig_marnie","ig_maryann","ig_maude","ig_michelle","ig_milton","ig_molly","ig_mrk","ig_mrs_thornhill","ig_mrsphillips","ig_natalia",
	"ig_nervousron","ig_nigel","ig_old_man1a","ig_old_man2","ig_omega","ig_oneil","ig_orleans","ig_ortega","ig_paper","ig_patricia","ig_priest","ig_prolsec_02",
	"ig_ramp_gang","ig_ramp_hic","ig_ramp_hipster","ig_ramp_mex","ig_roccopelosi","ig_russiandrunk","ig_screen_writer","ig_siemonyetarian","ig_solomon","ig_stevehains",
	"ig_stretch","ig_talina","ig_tanisha","ig_taocheng","ig_taostranslator","ig_tenniscoach","ig_terry","ig_tomepsilon","ig_tonya","ig_tracydisanto","ig_trafficwarden",
	"ig_tylerdix","ig_wade","ig_zimbor","mp_f_deadhooker","mp_f_freemode_01","mp_f_misty_01","mp_f_stripperlite","mp_g_m_pros_01","mp_headtargets","mp_m_claude_01",
	"mp_m_exarmy_01","mp_m_famdd_01","mp_m_fibsec_01","mp_m_freemode_01","mp_m_marston_01","mp_m_niko_01","mp_m_shopkeep_01","mp_s_m_armoured_01","player_one","player_two",
	"player_zero","s_f_m_fembarber","s_f_m_maid_01","s_f_m_shop_high","s_f_m_sweatshop_01","s_f_y_airhostess_01","s_f_y_bartender_01","s_f_y_baywatch_01","s_f_y_cop_01",
	"s_f_y_factory_01","s_f_y_hooker_01","s_f_y_hooker_02","s_f_y_hooker_03","s_f_y_migrant_01","s_f_y_movprem_01","s_f_y_ranger_01","s_f_y_scrubs_01","s_f_y_sheriff_01",
	"s_f_y_shop_low","s_f_y_shop_mid","s_f_y_stripper_01","s_f_y_stripper_02","s_f_y_stripperlite","s_f_y_sweatshop_01","s_m_m_ammucountry","s_m_m_armoured_01","s_m_m_armoured_02",
	"s_m_m_autoshop_01","s_m_m_autoshop_02","s_m_m_bouncer_01","s_m_m_chemsec_01","s_m_m_ciasec_01","s_m_m_cntrybar_01","s_m_m_dockwork_01","s_m_m_doctor_01","s_m_m_fiboffice_01",
	"s_m_m_fiboffice_02","s_m_m_gaffer_01","s_m_m_gardener_01","s_m_m_gentransport","s_m_m_hairdress_01","s_m_m_highsec_01","s_m_m_highsec_02","s_m_m_janitor","s_m_m_lathandy_01",
	"s_m_m_lifeinvad_01","s_m_m_linecook","s_m_m_lsmetro_01","s_m_m_mariachi_01","s_m_m_marine_01","s_m_m_marine_02","s_m_m_migrant_01","s_m_m_movalien_01","s_m_m_movprem_01",
	"s_m_m_movspace_01","s_m_m_paramedic_01","s_m_m_pilot_01","s_m_m_pilot_02","s_m_m_postal_01","s_m_m_postal_02","s_m_m_prisguard_01","s_m_m_scientist_01","s_m_m_security_01",
	"s_m_m_snowcop_01","s_m_m_strperf_01","s_m_m_strpreach_01","s_m_m_strvend_01","s_m_m_trucker_01","s_m_m_ups_01","s_m_m_ups_02","s_m_o_busker_01","s_m_y_airworker",
	"s_m_y_ammucity_01","s_m_y_armymech_01","s_m_y_autopsy_01","s_m_y_barman_01","s_m_y_baywatch_01","s_m_y_blackops_01","s_m_y_blackops_02","s_m_y_busboy_01","s_m_y_chef_01",
	"s_m_y_clown_01","s_m_y_construct_01","s_m_y_construct_02","s_m_y_cop_01","s_m_y_dealer_01","s_m_y_devinsec_01","s_m_y_dockwork_01","s_m_y_doorman_01","s_m_y_dwservice_01",
	"s_m_y_dwservice_02","s_m_y_factory_01","s_m_y_fireman_01","s_m_y_garbage","s_m_y_grip_01","s_m_y_hwaycop_01","s_m_y_marine_01","s_m_y_marine_02","s_m_y_marine_03",
	"s_m_y_mime","s_m_y_pestcont_01","s_m_y_pilot_01","s_m_y_prismuscl_01","s_m_y_prisoner_01","s_m_y_ranger_01","s_m_y_robber_01","s_m_y_sheriff_01","s_m_y_shop_mask",
	"s_m_y_strvend_01","s_m_y_swat_01","s_m_y_uscg_01","s_m_y_valet_01","s_m_y_waiter_01","s_m_y_winclean_01","s_m_y_xmech_01","s_m_y_xmech_02","u_f_m_corpse_01",
	"u_f_m_miranda","u_f_m_promourn_01","u_f_o_moviestar","u_f_o_prolhost_01","u_f_y_bikerchic","u_f_y_comjane","u_f_y_corpse_01","u_f_y_corpse_02","u_f_y_hotposh_01",
	"u_f_y_jewelass_01","u_f_y_mistress","u_f_y_poppymich","u_f_y_princess","u_f_y_spyactress","u_m_m_aldinapoli","u_m_m_bankman","u_m_m_bikehire_01","u_m_m_fibarchitect",
	"u_m_m_filmdirector","u_m_m_glenstank_01","u_m_m_griff_01","u_m_m_jesus_01","u_m_m_jewelsec_01","u_m_m_jewelthief","u_m_m_markfost","u_m_m_partytarget","u_m_m_prolsec_01",
	"u_m_m_promourn_01","u_m_m_rivalpap","u_m_m_spyactor","u_m_m_willyfist","u_m_o_finguru_01","u_m_o_taphillbilly","u_m_o_tramp_01","u_m_y_abner","u_m_y_antonb","u_m_y_babyd",
	"u_m_y_baygor","u_m_y_burgerdrug_01","u_m_y_chip","u_m_y_cyclist_01","u_m_y_fibmugger_01","u_m_y_guido_01","u_m_y_gunvend_01","u_m_y_hippie_01","u_m_y_imporage",
	"u_m_y_justin","u_m_y_mani","u_m_y_militarybum","u_m_y_paparazzi","u_m_y_party_01","u_m_y_pogo_01","u_m_y_prisoner_01","u_m_y_proldriver_01","u_m_y_rsranger_01",
	"u_m_y_sbike","u_m_y_staggrm_01","u_m_y_tattoo_01", "u_m_y_zombie_01" 
};